TakeHit logic
sopra-fs21-group-22/server pull request #93
Opened 2021-04-30 08:01 UTC by LexHeggli

added missed logic and adjusted some tests #89

2021-05-02 09:26 UTC, rob271 requested changes

2021-05-02 09:26 UTC, rob271 commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Player.java
>          if(onFieldCards.containsCardType(Card.BARREL)){
Player sött im beste fall nüt über en spezifische Card type wüsse. Chash do nöd eifach sowas mache?
isSafe = false
while(!isSafe):
    isSafe = blueCard.onBang(...)
    blueCard = next blueCard

2021-05-02 09:26 UTC, rob271 commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Player.java
>          if(onFieldCards.containsCardType(Card.BARREL)){
okey nöd ganz genau so wie ich gschriebe han logischerwiis. chunnsh aber scho druus was ich mein oder?

2021-05-02 09:26 UTC, rob271 commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Player.java
> +        }
do eigentlich nomol s'gliiche eifach bezüglich brownCards.

2021-05-02 10:24 UTC, LexHeggli commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Player.java
>          if(onFieldCards.containsCardType(Card.BARREL)){
yes, ech versuchs mol

2021-05-03 14:23 UTC, rob271 requested changes

2021-05-03 14:23 UTC, rob271 commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Hand.java
> +        return temp == null ? 0 : temp.size();
Do chöntsch doch sicher eifach direkt return playCard == null .... mache anstatt da mit temp oder?^^ Nöd dass es drufah chunt...

2021-05-03 14:23 UTC, rob271 commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Player.java
> +            isSafe = onFieldCards.get(i).onBang(this);
gits mehreri blaui charte wo da abfange chönd? wenn jo mush es break; inetue nöd dass zb s'bang scho abgfange worde isch und d'barrel denn tortzdem e  charte vom deck uf de ablage stapel tuet. Potentielle bug.

2021-05-03 14:23 UTC, rob271 commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/cards/brownCards/Missed.java
> +        onPlacement(affectedPlayer, targets);
Do cha me imfall au direkt onPlacement(affectedPlayer, new ArrayList<>()); schriibe. mush es nöd ändere has nur sege wölle.

2021-05-03 14:23 UTC, rob271 commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entity/Player.java
> +            i++;
Rueft da jetzt au Barrel.onBang() uf wenn es barrel i de hand hesh? gseht zumindest so us. falls es keine het wär en test für sowas je nochdem nice.

2021-05-04 10:11 UTC, merged